# Generated by Django 5.2.15 on 2026-07-02 12:24

import apps.classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_invite_code_submission_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='invite_code',
            field=models.CharField(default=apps.classroom.models.generate_random_invite_code, editable=False, max_length=10, unique=True),
        ),
    ]
