# Generated by Django 5.2.15 on 2026-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
